version: '3.3'

services:
  api:    
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:      
      - db
    volumes:
      - ./backend:/backend
    command: ./scripts/start.sh
    # entrypoint: ./scripts/entrypoint.sh 
    ports:
      - 8000:8005
    restart: always
    env_file: .env

  db:
    image: postgres:12
    container_name: postgres    
    env_file: .env
    ports:
        - "5431:5432"
    volumes:
        - ./data/:/var/lib/postgresql    
    

