version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/backend
    command: uvicorn app.main:app --reload --host=0.0.0.0 --port=8005
    ports:
      - 8000:8005
