"""db migration

Revision ID: 1ea2dc3cda2b
Revises: e1fd22338ba6
Create Date: 2022-04-26 15:00:48.563941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea2dc3cda2b'
down_revision = 'e1fd22338ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일'),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True, comment='수정일'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='이름'),
    sa.Column('nick_name', sa.String(length=20), nullable=False, comment='닉네임'),
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='전화번호'),
    sa.Column('email', sa.String(length=50), nullable=False, comment='이메일'),
    sa.Column('password', sa.String(length=2000), nullable=False, comment='비밀번호'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('users_auth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일'),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True, comment='수정일'),
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='전화번호'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='이메일'),
    sa.Column('auth_number', sa.String(length=10), nullable=False, comment='인증번호'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_users_auth_id'), 'users_auth', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_auth_id'), table_name='users_auth')
    op.drop_table('users_auth')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
