"""db migration

Revision ID: 3e0b36e6c6e8
Revises: 76369e8cf04e
Create Date: 2022-04-26 14:56:17.504503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e0b36e6c6e8'
down_revision = '76369e8cf04e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
