"""db migration

Revision ID: 70d53466427e
Revises: 84fb4ceb89f9
Create Date: 2022-04-26 13:49:52.200790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d53466427e'
down_revision = '84fb4ceb89f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_auth', sa.Column('auth_number', sa.String(length=10), nullable=False, comment='인증번호'))
    op.drop_column('users_auth', 'auth_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_auth', sa.Column('auth_text', sa.VARCHAR(length=10), autoincrement=False, nullable=False, comment='인증값'))
    op.drop_column('users_auth', 'auth_number')
    # ### end Alembic commands ###
