"""db migration

Revision ID: 76369e8cf04e
Revises: 70d53466427e
Create Date: 2022-04-26 14:32:55.838142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76369e8cf04e'
down_revision = '70d53466427e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_auth', 'name')
    op.drop_column('users_auth', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_auth', sa.Column('password', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='비밀번호'))
    op.add_column('users_auth', sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='이름'))
    # ### end Alembic commands ###
