"""db migration

Revision ID: 769663763448
Revises: 1ea2dc3cda2b
Create Date: 2022-04-27 00:02:25.571562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769663763448'
down_revision = '1ea2dc3cda2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_auth_email_key', 'users_auth', type_='unique')
    op.drop_column('users_auth', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_auth', sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='이메일'))
    op.create_unique_constraint('users_auth_email_key', 'users_auth', ['email'])
    # ### end Alembic commands ###
