"""db migration

Revision ID: 84fb4ceb89f9
Revises: 27daca63ab93
Create Date: 2022-04-26 12:26:03.931934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84fb4ceb89f9'
down_revision = '27daca63ab93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_auth', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='이름')
    op.alter_column('users_auth', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='이메일')
    op.alter_column('users_auth', 'password',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='비밀번호')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_auth', 'password',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_comment='비밀번호')
    op.alter_column('users_auth', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_comment='이메일')
    op.alter_column('users_auth', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_comment='이름')
    # ### end Alembic commands ###
