"""db migration

Revision ID: b93292ea7ef9
Revises: 3e0b36e6c6e8
Create Date: 2022-04-26 23:58:31.241881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b93292ea7ef9'
down_revision = '3e0b36e6c6e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
