"""db migration

Revision ID: e1fd22338ba6
Revises: b93292ea7ef9
Create Date: 2022-04-26 14:59:43.084165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1fd22338ba6'
down_revision = 'b93292ea7ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
