"""db migration

Revision ID: f51129073c15
Revises: 
Create Date: 2022-04-26 15:07:41.473793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f51129073c15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일'),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True, comment='수정일'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='이름'),
    sa.Column('nick_name', sa.String(length=20), nullable=False, comment='닉네임'),
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='전화번호'),
    sa.Column('email', sa.String(length=50), nullable=False, comment='이메일'),
    sa.Column('password', sa.String(length=50), nullable=False, comment='비밀번호'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
